/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as OtpVerificationRouteImport } from './../routes/otp-verification'
import { Route as LoginRouteImport } from './../routes/login'
import { Route as ForgotPasswordRouteImport } from './../routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './../routes/change-password'
import { Route as AdminRouteImport } from './../routes/admin'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as AdminIndexRouteImport } from './../routes/admin.index'
import { Route as AdminSupportRouteImport } from './../routes/admin.support'
import { Route as AdminSettingsRouteImport } from './../routes/admin.settings'
import { Route as AdminRolesRouteImport } from './../routes/admin.roles'
import { Route as AdminReviewsRouteImport } from './../routes/admin.reviews'
import { Route as AdminProfileRouteImport } from './../routes/admin.profile'
import { Route as AdminPaymentsRouteImport } from './../routes/admin.payments'
import { Route as AdminNotificationsRouteImport } from './../routes/admin.notifications'
import { Route as AdminMenuReviewRouteImport } from './../routes/admin.menu-review'
import { Route as AdminCustomersRouteImport } from './../routes/admin.customers'
import { Route as AdminCmsRouteImport } from './../routes/admin.cms'
import { Route as AdminChangePasswordRouteImport } from './../routes/admin.change-password'
import { Route as AdminCaterersRouteImport } from './../routes/admin.caterers'
import { Route as AdminBookingsRouteImport } from './../routes/admin.bookings'
import { Route as AdminAnalyticsRouteImport } from './../routes/admin.analytics'
import { Route as AdminSupportIdRouteImport } from './../routes/admin.support.$id'
import { Route as AdminMenuReviewIdRouteImport } from './../routes/admin.menu-review.$id'
import { Route as AdminCustomersIdRouteImport } from './../routes/admin.customers.$id'
import { Route as AdminCaterersIdRouteImport } from './../routes/admin.caterers.$id'
import { Route as AdminBookingsIdRouteImport } from './../routes/admin.bookings.$id'

const OtpVerificationRoute = OtpVerificationRouteImport.update({
  id: '/otp-verification',
  path: '/otp-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuReviewRoute = AdminMenuReviewRouteImport.update({
  id: '/menu-review',
  path: '/menu-review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChangePasswordRoute = AdminChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCaterersRoute = AdminCaterersRouteImport.update({
  id: '/caterers',
  path: '/caterers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportIdRoute = AdminSupportIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSupportRoute,
} as any)
const AdminMenuReviewIdRoute = AdminMenuReviewIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminMenuReviewRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCustomersRoute,
} as any)
const AdminCaterersIdRoute = AdminCaterersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCaterersRoute,
} as any)
const AdminBookingsIdRoute = AdminBookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBookingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp-verification': typeof OtpVerificationRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/caterers': typeof AdminCaterersRouteWithChildren
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/menu-review': typeof AdminMenuReviewRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/caterers/$id': typeof AdminCaterersIdRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/menu-review/$id': typeof AdminMenuReviewIdRoute
  '/admin/support/$id': typeof AdminSupportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp-verification': typeof OtpVerificationRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/caterers': typeof AdminCaterersRouteWithChildren
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/menu-review': typeof AdminMenuReviewRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/caterers/$id': typeof AdminCaterersIdRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/menu-review/$id': typeof AdminMenuReviewIdRoute
  '/admin/support/$id': typeof AdminSupportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/otp-verification': typeof OtpVerificationRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/caterers': typeof AdminCaterersRouteWithChildren
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/menu-review': typeof AdminMenuReviewRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/bookings/$id': typeof AdminBookingsIdRoute
  '/admin/caterers/$id': typeof AdminCaterersIdRoute
  '/admin/customers/$id': typeof AdminCustomersIdRoute
  '/admin/menu-review/$id': typeof AdminMenuReviewIdRoute
  '/admin/support/$id': typeof AdminSupportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/otp-verification'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/caterers'
    | '/admin/change-password'
    | '/admin/cms'
    | '/admin/customers'
    | '/admin/menu-review'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/'
    | '/admin/bookings/$id'
    | '/admin/caterers/$id'
    | '/admin/customers/$id'
    | '/admin/menu-review/$id'
    | '/admin/support/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/otp-verification'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/caterers'
    | '/admin/change-password'
    | '/admin/cms'
    | '/admin/customers'
    | '/admin/menu-review'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/support'
    | '/admin'
    | '/admin/bookings/$id'
    | '/admin/caterers/$id'
    | '/admin/customers/$id'
    | '/admin/menu-review/$id'
    | '/admin/support/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/otp-verification'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/caterers'
    | '/admin/change-password'
    | '/admin/cms'
    | '/admin/customers'
    | '/admin/menu-review'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/'
    | '/admin/bookings/$id'
    | '/admin/caterers/$id'
    | '/admin/customers/$id'
    | '/admin/menu-review/$id'
    | '/admin/support/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OtpVerificationRoute: typeof OtpVerificationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/otp-verification': {
      id: '/otp-verification'
      path: '/otp-verification'
      fullPath: '/otp-verification'
      preLoaderRoute: typeof OtpVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu-review': {
      id: '/admin/menu-review'
      path: '/menu-review'
      fullPath: '/admin/menu-review'
      preLoaderRoute: typeof AdminMenuReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/change-password': {
      id: '/admin/change-password'
      path: '/change-password'
      fullPath: '/admin/change-password'
      preLoaderRoute: typeof AdminChangePasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/caterers': {
      id: '/admin/caterers'
      path: '/caterers'
      fullPath: '/admin/caterers'
      preLoaderRoute: typeof AdminCaterersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support/$id': {
      id: '/admin/support/$id'
      path: '/$id'
      fullPath: '/admin/support/$id'
      preLoaderRoute: typeof AdminSupportIdRouteImport
      parentRoute: typeof AdminSupportRoute
    }
    '/admin/menu-review/$id': {
      id: '/admin/menu-review/$id'
      path: '/$id'
      fullPath: '/admin/menu-review/$id'
      preLoaderRoute: typeof AdminMenuReviewIdRouteImport
      parentRoute: typeof AdminMenuReviewRoute
    }
    '/admin/customers/$id': {
      id: '/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/admin/caterers/$id': {
      id: '/admin/caterers/$id'
      path: '/$id'
      fullPath: '/admin/caterers/$id'
      preLoaderRoute: typeof AdminCaterersIdRouteImport
      parentRoute: typeof AdminCaterersRoute
    }
    '/admin/bookings/$id': {
      id: '/admin/bookings/$id'
      path: '/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AdminBookingsIdRouteImport
      parentRoute: typeof AdminBookingsRoute
    }
  }
}

interface AdminBookingsRouteChildren {
  AdminBookingsIdRoute: typeof AdminBookingsIdRoute
}

const AdminBookingsRouteChildren: AdminBookingsRouteChildren = {
  AdminBookingsIdRoute: AdminBookingsIdRoute,
}

const AdminBookingsRouteWithChildren = AdminBookingsRoute._addFileChildren(
  AdminBookingsRouteChildren,
)

interface AdminCaterersRouteChildren {
  AdminCaterersIdRoute: typeof AdminCaterersIdRoute
}

const AdminCaterersRouteChildren: AdminCaterersRouteChildren = {
  AdminCaterersIdRoute: AdminCaterersIdRoute,
}

const AdminCaterersRouteWithChildren = AdminCaterersRoute._addFileChildren(
  AdminCaterersRouteChildren,
)

interface AdminCustomersRouteChildren {
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersIdRoute: AdminCustomersIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminMenuReviewRouteChildren {
  AdminMenuReviewIdRoute: typeof AdminMenuReviewIdRoute
}

const AdminMenuReviewRouteChildren: AdminMenuReviewRouteChildren = {
  AdminMenuReviewIdRoute: AdminMenuReviewIdRoute,
}

const AdminMenuReviewRouteWithChildren = AdminMenuReviewRoute._addFileChildren(
  AdminMenuReviewRouteChildren,
)

interface AdminSupportRouteChildren {
  AdminSupportIdRoute: typeof AdminSupportIdRoute
}

const AdminSupportRouteChildren: AdminSupportRouteChildren = {
  AdminSupportIdRoute: AdminSupportIdRoute,
}

const AdminSupportRouteWithChildren = AdminSupportRoute._addFileChildren(
  AdminSupportRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRouteWithChildren
  AdminCaterersRoute: typeof AdminCaterersRouteWithChildren
  AdminChangePasswordRoute: typeof AdminChangePasswordRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminMenuReviewRoute: typeof AdminMenuReviewRouteWithChildren
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRouteWithChildren,
  AdminCaterersRoute: AdminCaterersRouteWithChildren,
  AdminChangePasswordRoute: AdminChangePasswordRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminMenuReviewRoute: AdminMenuReviewRouteWithChildren,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OtpVerificationRoute: OtpVerificationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from '../router.jsx'
import type { startInstance } from '../start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
